# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  schedule:
    - cron: '*/15 * * * *'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn  

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: authenticate
        run: |
          git config --global user.email "fastsvc@microsoft.com"
          git config --global user.name "Fast Service Test"
        
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN}}
      - run: yarn
      - name: NPM PUBLISH
        run: yarn publish-ci -n $NPM_SECRET_TOKEN
        env:
          NPM_SECRET_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
       
  
